if true then return {} end

--
--
-- return {
--   "AstroNvim/astrolsp",
--   opts = {
--     autocmds = {
--       -- This force-runs the "Smart" LSP organize imports on save
--       gopls_organize_imports = {
--         {
--           event = "BufWritePre",
--           pattern = "*.go",
--           callback = function()
--             local params = vim.lsp.util.make_range_params()
--             params.context = { only = { "source.organizeImports" } }
--             -- Synchronous call to ensure it finishes before saving
--             vim.lsp.buf_request_sync(0, "textDocument/codeAction", params, 1000)
--           end,
--         },
--       },
--     },
--     -- Ensure gopls is configured to help
--     config = {
--       gopls = {
--         settings = {
--           gopls = {
--             completeUnimported = true,
--              usePlaceholders = true,
--             analyses = {
--               unusedparams = true,
--             },
--             staticcheck = true,
--
--             -- Add this to help differentiate packages
--             directoryFilters = { "-**/node_modules", "-.git" },
--           },
--         },
--       },
--     },
--   },
-- }
